name: Publish to GitHub Packages

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: '1.25.7'
      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.56.6
      # - run: aqua install ## aquaproj/aqua-installerでやるので不要
      - run: task audit
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: task lint
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: task test
      - run: task build-go
      - run: task build-docker
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}:latest
          IMAGE_SHA=ghcr.io/${{ github.repository }}:${{ github.sha }}
          docker tag go-docker-clock $IMAGE_NAME
          docker tag go-docker-clock $IMAGE_SHA
          docker push $IMAGE_NAME
          docker push $IMAGE_SHA
