name: Publish to GitHub Packages

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: '1.25'
      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.43.1
      # - run: aqua install ## 不要
      - run: task audit
      - run: task lint
      - run: task test
      - run: task build-go
      - run: task build-docker
